services:
  kuzco-main:
    container_name: kuzco-main
    build: .
    networks:
      - kuzco-network
    restart: always
    environment:
      NODE_ENV: "production"
      KUZCO_WORKER: "8NP0GC_HxrCcV-dIhG7Uu"
      KUZCO_CODE: "f8d6812a-85a5-4d89-aaeb-1d73d54ade20"
    volumes:
      - ./cache:/app/cache  # Tambahkan volume agar cache bisa persist jika diperlukan

networks:
  kuzco-network:
    driver: bridge
